"""
Used to populate the newly created schema that stores emmision info.
Inserts data into cg_chem for emissions from chemicals.
Created from pesticides.
"""

import SaveDataHelper


class Chemical(SaveDataHelper.SaveDataHelper):
    """
    Evaluate the VOC emissions generated by the application of chemical fertilizers
    """

    def __init__(self, cont):
        """

        :param cont:
        """
        SaveDataHelper.SaveDataHelper.__init__(self, cont)
        self.document_file = "Chemical"

        self.cont = cont
        self.kvals = cont.get('kvals')

    def regional_chem(self, feed, yr):
        """
        Add chemical emissions to database tables using regional crop budget

        :param feed: feedstock
        :param yr: budget year (for energy crops)
        :return:

        """

        # set year for crop budget
        self.kvals['yr'] = yr

        # set crop type
        self.kvals['feed'] = feed.lower()

        if feed == 'SG':
            till_dict = {'NT': 'notill'}
        elif feed == 'MS':
            till_dict = {'CT': 'convtill'}
        else:
            till_dict = {'CT': 'convtill',
                         'RT': 'reducedtill',
                         'NT': 'notill'}

        for tillage in till_dict:
            self.kvals['tillage'] = tillage
            self.kvals['tillage_name'] = till_dict[tillage]

            # set tillage selection for data (if RT then same as CT)
            if tillage == 'RT':
                self.kvals['tillage_select'] = 'CT'
            else:
                self.kvals['tillage_select'] = tillage

            chem_query = """INSERT INTO {scenario_name}.{feed}_chem
                             SELECT  feed.fips,
                                     '{tillage}',
                                     '{yr}',
                                     (2461850051) AS SCC,
                                     (feed.{tillage_name}_harv_ac * (chem.pest_app * 0.9 * 0.835) * 0.907018474 / 2000.0) AS VOC,
                                     'Pesticide Emissions' AS Description
                             FROM {production_schema}.{feed}_data feed
                             LEFT JOIN (SELECT fips, sum(herb_lbac + insc_lbac) as pest_app
                                        FROM {production_schema}.{feed}_equip_fips
                                        WHERE tillage = '{tillage_select}' AND bdgtyr = '{yr}'
                                        GROUP BY fips) chem
                             ON chem.fips = feed.fips
                             GROUP BY feed.fips;""".format(**self.kvals)
            self._execute_query(chem_query)

    def set_chemical(self, feed):
        """
        Find the feedstock and add emmissions if it is switch grass or corn grain.

        :param feed: Feedstock
        :return:
        """

        query = None

        if feed == 'CG':
            query = self.__corn_grain__()
        elif feed == 'SG':
            query = self.__switchgrass__()

        # if a query was made, execute it.
        if query is not None:
            self._execute_query(query)

    def __corn_grain__(self):
        """
        emmisions = harvested acres * lbs/acre * Evaporation rate * VOC content (lbs VOC / lb active ingridient) * conversion from lbs to mt.
        emmisions = total VOC emmisions (lbs VOC).
        total_harv_ac = total harvested acres. (acres)
        pest.EF = lbs VOC/acre.
        .9 =  evaporation rate. (lbs active/lbs VOC)
        .835 = voc content. lbs VOC / lb active ingridient.
        (acres) * (lbs VOC/acre) * (lbs active/lbs VOC) * (lbs VOC/lbs active) * (mt/lbs) = mt VOC

        :return: SQL
        """

        till_dict = {'CT': 'convtill',
                     'RT': 'reducedtill',
                     'NT': 'notill'}

        for till in till_dict:
            self.kvals['till'] = till
            self.kvals['tillage'] = till_dict[till]
            chem_query = """INSERT INTO {scenario_name}.{cg_chem_table}
                            (
                            SELECT  cg.fips,
                                    '{till}',
                                    '1',
                                    (2461850051) AS SCC,
                                    ((cg.{tillage}_harv_ac * pest.EF * 0.9 * 0.835) * 0.907018474 / 2000.0) AS VOC,
                                    ('Pesticide Emissions') AS Description
                            FROM {production_schema}.{cg_table} cg, {constants_schema}.cg_pest_app_factor pest
                            WHERE substr(fips, 1, 2) = pest.STFIPS
                            )""".format(**self.kvals)

            return chem_query

    def __switchgrass__(self):
        """
        Recieves several different fertilizers: Quinclorac, Attrazine, 2 and 4-D-Amine
        Multiply by .1 b/c it is switch grass on a ten year cycle.
        emmisions = .1 * harvested acres * lbs/acre * Evaporation rate * VOC content (lbs VOC / lb active ingridient) * conversion lbs to mt  VOC
        emmisions (mt VOC)

        :return: SQL
        """
        kvals = self.kvals

        # yearly percent
        kvals['yr_pct'] = 0.1

        # pesticide amount for each year in cycle
        crop_years = {1: 2.5,  # @TODO: remove hardcoded year allocations
                      2: 0.0,
                      3: 0.0,
                      4: 0.0,
                      5: 1.5,
                      6: 0.0,
                      7: 0.0,
                      8: 0.0,
                      9: 0.0,
                      10: 0.0}

        chem_query = ''

        # process non-zero years
        for year in crop_years:
            kvals['year'] = year
            kvals['pest_amt'] = crop_years[year]

            chem_query += """INSERT INTO {scenario_name}.{sg_chem_table}
                             (
                             SELECT sg.fips,
                                    'NT',
                                    '{year}',
                                     2461850099 AS SCC,
                                     sg.notill_harv_ac * {yr_pct} * {pest_amt} * 0.9 * 0.835 * 0.90718474 / 2000.0 AS VOC,
                                     'Pesticide Emissions' AS Description
                             FROM {production_schema}.{sg_table} sg
                             );""".format(**self.kvals)

        return chem_query
