# -*- coding: utf-8 -*-
"""
Created on Thur Mar 3 9:24:46 2016

Populates tables for transportation emissions associated with off-farm transport

Inputs include:
    list of feedstock types (feedstock_list)
    container (cont)

@author: aeberle
"""

import SaveDataHelper
from src.AirPollution.utils import config, logger


class Transportation(SaveDataHelper.SaveDataHelper):
    """
    Computes the emissions associated with off-farm transportation
    """

    def __init__(self, feed, cont, fips):
        """

        :param feed: feedstock to process
        :param cont: Container object
        :param fips: FIPS code
        :return:
        """
        SaveDataHelper.SaveDataHelper.__init__(self, cont)
        self.feed = feed
        self.document_file = "Logistics"  # filename for saving queries to text file for debugging

        self.kvals = dict()
        # set production schema and scenario name
        self.kvals['production_schema'] = config.get('production_schema')
        self.kvals['scenario_name'] = config.get('title')

        self.column_dict = dict()
        # create dictionary for column names for production data
        self.column_dict['CG'] = 'total_prod'
        self.column_dict['CS'] = 'prod'
        self.column_dict['WS'] = 'prod'
        self.column_dict['SG'] = 'prod'
        self.column_dict['FR'] = 'fed_minus_55'

        self.db_in = "fips_" + fips + "_" + feed + "_in"  # input database for MOVES runs
        self.db_in = "fips_" + fips + "_" + feed + "_out"  # input database for MOVES runs

    def process_moves_data(self):
        """
        Post-process MOVES outputs to compute total combustion emissions from off-farm transport
        Update transportation table with these values

        Call function to compute total running emissions per trip
        Call function to compute total start emissions per trip
        Call function to compute total resting evaporative emissions per trip (currently zero)
        """
        logger.info('Post-processing MOVES output for %s' % self.feed)

        self.calc_run_emission()
        self.calc_start_emissions()
        self.calc_rest_evap_emissions()

    def calc_run_emission(self):
        """
        Total running emissions per trip (by pollutant) = sum over i = 1 to 16 for (SELECT sum(ratePerDistance * vmtfrac_in_speedbin[i] * vmt)
                                                                                    FROM output.rateperdistance
                                                                                    WHERE pollutantID = value AND (processID = 2 OR processID = 16) AND avgSpeedBinID = i)
        """
        logger.debug('Calculating running emissions')
        # @TODO: replace with code for processing MOVES outputs
        pass

    def calc_start_emissions(self):
        """
        Total start emissions per trip (by pollutant) = SELECT sum(output.ratePerVehicle * pop)
                                                        FROM output.ratepervehicle
                                                        WHERE pollutantID = value AND (processID = 17 OR processID = 90 OR processID = 91)
        """
        logger.debug('Calculating start emissions')
        # @TODO: replace with code for processing MOVES outputs
        pass

    def calc_rest_evap_emissions(self):
        """
        Total resting evaporative fuel vapor venting rates are set to zero because only using 12 hr time span and resting evaporative rates require 24 hr selection
        :return:
        """
        logger.debug('Calculating resting evaporative fuel vapor venting emissions')
        logger.warning('Resting evaporative fuel vapor venting rates are currently zero')
        # @TODO: replace with code for processing MOVES outputs
        pass

    def transport_fugitive_dust(self):
        """
        Compute fugitive dust emissions generated by off-farm transportation
        Update transportation table with these values
        """
        # @TODO: replace with code for calculating fugitive dust
        pass

    def calculate_transport_emissions(self):
        """
        Calculate fugitive dust and combustion emissions generated by off-farm transportation
        Update transportation table with these values
        """
        self.process_moves_data()
        self.transport_fugitive_dust()
